### ISSUE TITLE
(YOUR) Home directory apears when publishing

### ISSUE THREAD

**Issue by eserrasanz** [gzzo/s3_pypi_publisher#1]
virtualenv venv -p python3
source venv/bin/activate
pip install s3_pypi_publisher
cd <MYPTOJECT>
publish_package

-bash: <PATH/TO>/venv/bin/publish_package: /Users/guido/.local/share/virtualenvs/s3_pypi_publisher-j7I5i9b4/bin/python: bad interpreter: No such file or directory

**Comment by gzzo** [comment]
Can you try `pip install -U s3_pypi_publisher` and see if the version I just pushed fixed it for you? You should be on 0.1.1

**Comment by eserrasanz** [comment]
like a charm thanks
